### ISSUE TITLE
Importing this component into an unmodified sapper w/ rollup project results in this error

### ISSUE THREAD

**Issue by ghotiphud** [sveltejs/svelte-virtual-list#25]
```
node_modules/@sveltejs/svelte-virtual-list/VirtualList.svelte:1
<script>
^

SyntaxError: Unexpected token <
    at Module._compile (internal/modules/cjs/loader.js:720:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/mnt/shared/dev/comicsub/__sapper__/dev/server/server.js:11:35)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)```

**Comment by ghotiphud** [comment]
Adding it as a devDependency fixes the error, but results in no items rendered with this code:

```
<script>
  import VirtualList from "@sveltejs/svelte-virtual-list";

  const things = [
    // these can be any values you like
    { name: "one", number: 1 },
    { name: "two", number: 2 },
    { name: "three", number: 3 },
    { name: "six thousand and ninety-two", number: 6092 }
  ];
</script>

<style>
  .container {
    border: 1px solid red;
  }
</style>

<div class="container">
  <VirtualList items={things} let:item>
    <p>{item.number}: {item.name}</p>
  </VirtualList>
</div>
```

**Comment by ghotiphud** [comment]
adding height="500px" allows it to display, so I guess it was a styling issue...

**Comment by matthewdbadcock** [comment]
I think this should be added to the readme, we shouldnt really have to dig through closed issues to fix something like this

**Comment by kevlened** [comment]
I ran into the same issue using Sapper, but I didn't want to set the height to fix it. Importing the component directly worked.

```html
<script>
  import VirtualList from '@sveltejs/svelte-virtual-list/VirtualList.svelte';

  // ...
</script>
```
